# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb5c241e0075d53e793391bdadc5ae53dc5e989d3fd38caaf9666031ea7caf7fd04f452d376ae01bd48bb9e8c1545787529a26c3ff4f11c374948e0e24ebb8c

test:
  secret_key_base: f3eed80fdee062a9c6861881b93456be70e579a6f937cb9dd13bf10a4cac661d6306ec4d1dc44e08adb9256f9714cadac43356aa4ba465a8107689ce1d6da309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
